#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APX.Xrm
{
	
	
	/// <summary>
	/// Custom Entity 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("apx_location")]
	public partial class APX_Location : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the apx_location entity
		/// </summary>
		public partial class Fields
		{
			public const string apx_Contact = "apx_contact";
			public const string apx_ContactName = "apx_contactname";
			public const string apx_ContactYomiName = "apx_contactyominame";
			public const string apx_apx_Location_apx_Trips_Location = "apx_apx_Location_apx_Trips_Location";
			public const string apx_DeSc = "apx_desc";
			public const string apx_ExternalPrimaryKey = "apx_externalprimarykey";
			public const string apx_Location_Contact_Contact = "apx_Location_Contact_Contact";
			public const string apx_LocationId = "apx_locationid";
			public const string Id = "apx_locationid";
			public const string apx_Name = "apx_name";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public APX_Location(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public APX_Location(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public APX_Location(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public APX_Location() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "apx_locationid";
		
		public const string PrimaryNameAttribute = "apx_name";
		
		public const string EntitySchemaName = "apx_Location";
		
		public const string EntityLogicalName = "apx_location";
		
		public const string EntityLogicalCollectionName = "apx_locations";
		
		public const string EntitySetName = "apx_locations";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_contact")]
		public Microsoft.Xrm.Sdk.EntityReference apx_Contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("apx_contact");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("apx_contact", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_contactname")]
		public string apx_ContactName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("apx_contact"))
				{
					return this.FormattedValues["apx_contact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_contactyominame")]
		public string apx_ContactYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("apx_contact"))
				{
					return this.FormattedValues["apx_contact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_desc")]
		public string apx_DeSc
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("apx_desc");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("apx_desc", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_externalprimarykey")]
		public System.Nullable<int> apx_ExternalPrimaryKey
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("apx_externalprimarykey");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("apx_externalprimarykey", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_locationid")]
		public System.Nullable<System.Guid> apx_LocationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("apx_locationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("apx_locationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_locationid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.apx_LocationId = value;
			}
		}
		
		/// <summary>
		/// Primary attribute
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_name")]
		public string apx_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("apx_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("apx_name", value);
			}
		}
		
		/// <summary>
		/// 1:N apx_apx_location_apx_trips_Location
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("apx_apx_location_apx_trips_Location")]
		public System.Collections.Generic.IEnumerable<APX.Xrm.apx_Trips> apx_apx_Location_apx_Trips_Location
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<APX.Xrm.apx_Trips>("apx_apx_location_apx_trips_Location", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<APX.Xrm.apx_Trips>("apx_apx_location_apx_trips_Location", null, value);
			}
		}
		
		/// <summary>
		/// N:1 apx_Location_Contact_Contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("apx_contact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("apx_Location_Contact_Contact")]
		public APX.Xrm.Contact apx_Location_Contact_Contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<APX.Xrm.Contact>("apx_Location_Contact_Contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<APX.Xrm.Contact>("apx_Location_Contact_Contact", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public APX_Location(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["apx_locationid"] = base.Id;
                        break;
                    case "apx_locationid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
